sample-app/config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"

  devise_for :buyers
  devise_for :sellers

  resources :orders, :only => [:create, :destroy]

  resources :categories, :only => [:show, :index]

  get 'products/:id/sold' => 'products#sold', as: :product_sold
  post 'products/search' => 'products#search'
  resources :products, :only => [:show, :edit, :update, :new, :create, :index]

  get 'sellers/sold' => 'sellers#sold', as: :seller_sold
  get 'sellers/:id/products' => 'sellers#products', as: :seller_products
  resources :sellers, :only => [:show, :index]

  get 'buyers/orders' => 'buyers#orders', as: :buyer_orders
  resources :buyers, :only => [:show]

end

sample-app/app/models/buyer.rb
class Buyer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

sample-app/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product_categories
  has_many :products, through: :product_categories
end

sample-app/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :buyer
  belongs_to :product
end

sample-app/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :seller
  has_many :orders
  has_many :product_categories
  has_many :categories, through: :product_categories
end

sample-app/app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

sample-app/app/models/seller.rb
class Seller < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
end

sample-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

sample-app/app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: [:show]

  # GET /buyers/1
  # GET /buyers/1.json
  def show
  end

  # GET /buyers/orders
  def orders
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_params
      params.require(:buyer).permit(:email, :name)
    end
end

sample-app/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = @category.products
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

sample-app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

sample-app/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_buyer!, except: [:show]
  before_action :set_order, only: [:show, :destroy]
  before_action :order_buyer, only: [:show, :destroy]

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.buyer = current_buyer

    respond_to do |format|
      if @order.save
        format.html { redirect_to buyer_orders_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to buyer_orders_path, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:buyer_id, :product_id, :created_at)
    end

    def order_buyer
      redirect_to root_path unless @order.buyer == current_buyer
    end
end

sample-app/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_seller!, except: [:show, :index, :sold]
  before_action :set_product, only: [:show, :edit, :update, :destroy, :sold]
  before_action :product_seller, only: [:edit, :update, :sold]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  def search
    @search = params['product']['search']
    @products = Product.all.where('name like ?', "%#{@search}%")
    render :index
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @order = Order.new
    @order.product = @product
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.seller = current_seller

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /products/1/sold
  def sold
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:seller_id, :name, :cost, :category_ids => [])
    end

    def product_seller
      redirect_to root_path unless @product.seller == current_seller
    end
end

sample-app/app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :products]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
  end

  # GET /sellers/1/products
  def products
    @products = @seller.products
  end

  def sold
    @orders = current_seller.products.map do |p|
      p.orders
    end .flatten.sort do |a, b|
      b.created_at <=> a.created_at
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:email, :name)
    end
end

sample-app/app/helpers/application_helper.rb
module ApplicationHelper
end

sample-app/app/helpers/buyers_helper.rb
module BuyersHelper
end

sample-app/app/helpers/categories_helper.rb
module CategoriesHelper
end

sample-app/app/helpers/home_helper.rb
module HomeHelper
end

sample-app/app/helpers/orders_helper.rb
module OrdersHelper
end

sample-app/app/helpers/products_helper.rb
module ProductsHelper
end

sample-app/app/helpers/sellers_helper.rb
module SellersHelper
end

sample-app/app/views/buyers/index.html.erb
<h1>Listing buyers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buyers.each do |buyer| %>
      <tr>
        <td><%= buyer.email %></td>
        <td><%= buyer.name %></td>
        <td><%= link_to 'Show', buyer %></td>
        <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
        <td><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buyer', new_buyer_path %>

sample-app/app/views/buyers/orders.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>商品</th>
      <th>価格</th>
      <th>購入日</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% current_buyer.orders.each do |order| %>
      <tr>
        <td><%= link_to order.product.name, product_path(order.product) %></td>
        <td><%= order.product.cost %></td>
        <td><%= order.created_at %></td>
        <td><%= link_to "キャンセル", order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

sample-app/app/views/buyers/show.html.erb
<dl class="dl-horizontal">
  <dt>メールアドレス</dt>
  <dd><%= @buyer.email %></dd>
  <dt>名前</dt>
  <dd><%= @buyer.name %></dd>
</dl>

sample-app/app/views/categories/index.html.erb
<h1>カテゴリ一覧</h1>

<ul id="category-list" class="animated-list">
  <% @categories.each do |category| %>
    <li class="animated-list-content">
      <%= link_to content_tag(:span, category.name), category %>
    </li>
  <% end %>
</ul>

sample-app/app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<%= render 'products/list', locals: { products: @products } %>

sample-app/app/views/home/index.html.erb
<h1>計算機科学実験演習用デモアプリケーション</h1>

<%= link_to 'repository', 'https://github.com/tyage/experiment-4-db' %>

sample-app/app/views/layouts/_header.html.erb
<nav id="header-nav" class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'top', root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to '販売者一覧', sellers_path %></li>
      <li><%= link_to '商品一覧', products_path %></li>
      <li><%= link_to 'カテゴリ一覧', categories_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_seller %>
        <li><%= link_to '商品管理', seller_products_path(current_seller) %></li>
        <li><%= link_to 'マイページ', seller_path(current_seller) %></li>
        <li><%= link_to 'アカウント設定', edit_seller_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_seller_session_path, :method => :delete %></li>
      <% elsif current_buyer %>
        <li><%= link_to '注文履歴', buyer_orders_path %></li>
        <li><%= link_to 'マイページ', buyer_path(current_buyer) %></li>
        <li><%= link_to 'アカウント設定', edit_buyer_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_buyer_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to '販売者ログイン', seller_session_path %></li>
        <li><%= link_to '購買者ログイン', buyer_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

sample-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <%= render 'layouts/header' %>
</header>

<div class="container">
  <% if notice %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-warning"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

sample-app/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :product_id %>
  <div class="actions">
    <%= f.submit "購入する", class: "btn btn-default" %>
  </div>
<% end %>

sample-app/app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Buyer</th>
      <th>Product</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.buyer_id %></td>
        <td><%= order.product_id %></td>
        <td><%= order.created_at %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

sample-app/app/views/orders/show.html.erb
<p>
  <strong>Buyer:</strong>
  <%= @order.buyer_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order.product_id %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @order.created_at %>
</p>

<%= link_to 'Back', buyer_orders_path %>

sample-app/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "商品名" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :categories, "カテゴリ" %>
    <div class="checkbox">
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
        <label>
          <%= b.check_box %>
          <%= b.text %>
        </label>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :cost, "価格" %>
    <%= f.number_field :cost, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "送信", class: "btn btn-default" %>
  </div>
<% end %>

sample-app/app/views/products/_list.html.erb
<ul class="product-list animated-list">
  <% @products.each do |product| %>
    <li class="product animated-list-content">
      <p class="product-image">
        <%= link_to(product) do %>
          <img src="/assets/product-default.jpg" alt="">
        <% end %>
      </p>
      <p><%= link_to product.name, product %></p>
      <p>¥<%= product.cost %></p>
      <% if product.seller == current_seller %>
        <p><%= link_to '編集', edit_product_path(product) %></p>
      <% end %>
    </li>
  <% end %>
</ul>

sample-app/app/views/products/edit.html.erb
<%= link_to '商品ページ', @product %>

<h1>商品を編集</h1>

<%= render 'form' %>

<%= link_to 'Back', seller_products_path(current_seller) %>

sample-app/app/views/products/index.html.erb
<h1>商品一覧</h1>

<div class="row" id="product-search-form">
<%= form_for(:product, url: products_search_path) do |f| %>
  <div class="col-xs-3">
    <%= f.search_field :search, class: 'form-control', value: @search %>
  </div>
  <%= f.submit '商品名で検索' %>
<% end %>
</div>

<%= render 'list', locals: { products: @products } %>

sample-app/app/views/products/new.html.erb
<h1>商品を追加</h1>

<%= render 'form' %>

<%= link_to 'Back', seller_products_path(current_seller) %>

sample-app/app/views/products/orders.html.erb
<h1><%= @product.name %>の購入履歴</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>購入者</th>
      <th>購入日時</th>
    </tr>
  </thead>
  <tbody>
    <% @product.orders.each do |order| %>
      <tr>
        <td><%= link_to order.buyer.name, order.buyer %></td>
        <td><%= order.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

sample-app/app/views/products/show.html.erb
<div id="product-detail">
  <div id="product-image">
    <img src="/assets/product-default.jpg" alt="">
  </div>

  <dl class="dl-horizontal">
    <dt>商品名</dt>
    <dd><%= @product.name %></dd>
    <dt>価格</dt>
    <dd>¥<%= @product.cost %></dd>
    <dt>カテゴリ</dt>
    <dd>
      <% @product.categories.each do |category| %>
        <%= link_to category.name, category %>
      <% end %>
    </dd>
    <dt>販売者</dt>
    <dd><%= link_to @product.seller.name, seller_path(@product.seller) %></dd>
  </dl>

  <% if current_buyer %>
    <%= render 'orders/form' %>
  <% end %>

  <% if @product.seller == current_seller %>
    <%= link_to '編集', edit_product_path(@product) %>
    <%= link_to '販売履歴', product_sold_path(@product) %>
  <% end %>
</div>

sample-app/app/views/products/sold.html.erb
<h1><%= @product.name %>の販売履歴</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>購入者</th>
      <th>購入日時</th>
    </tr>
  </thead>
  <tbody>
    <% @product.orders.each do |order| %>
      <tr>
        <td><%= link_to order.buyer.name, order.buyer %></td>
        <td><%= order.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

sample-app/app/views/sellers/index.html.erb
<h1>販売者一覧</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>名前</th>
      <th>メールアドレス</th>
    </tr>
  </thead>

  <tbody>
    <% @sellers.each do |seller| %>
      <tr>
        <td><%= link_to seller.name, seller_path(seller) %></td>
        <td><%= seller.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

sample-app/app/views/sellers/products.html.erb
<h1><%= @seller.name %>の商品一覧</h1>

<% if @seller == current_seller %>
  <%= link_to '商品追加', new_product_path %>
  <%= link_to '販売履歴', seller_sold_path %>
<% end %>

<%= render 'products/list', locals: { products: @products } %>

sample-app/app/views/sellers/show.html.erb
<dl class="dl-horizontal">
  <dt>メールアドレス</dt>
  <dd><%= @seller.email %></dd>
  <dt>名前</dt>
  <dd><%= @seller.name %></dd>
</dl>

<%= link_to '販売商品一覧', seller_products_path(@seller) %>

sample-app/app/views/sellers/sold.html.erb
<h1>販売履歴</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>商品</th>
      <th>購入者</th>
      <th>購入日時</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.product.name, order.product %></td>
        <td><%= link_to order.buyer.name, order.buyer %></td>
        <td><%= order.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>